### ISSUE TITLE
Re-add simple web console for input/output

### ISSUE THREAD

**Issue by srowen** [OryxProject/oryx#116]
It might be useful to reintroduce the simple HTML page that let people enter queries to endpoints from the browser.

**Comment by kkasravi** [comment]
I'm working on a UI dashboard on another [project](https://github.com/intel-hadoop/gearpump). Do you have an idea of the various console features?

**Comment by srowen** [comment]
Oh, even better! the HTML already exists in about 90% the form we need. It is a combination of the template HTML found in:

https://github.com/cloudera/oryx/blob/master/serving/src/main/jspx/index.jspx
and
https://github.com/cloudera/oryx/blob/master/als-serving/src/main/jspx/test-als.jspx
https://github.com/cloudera/oryx/blob/master/kmeans-serving/src/main/jspx/test-kmeans.jspx
https://github.com/cloudera/oryx/blob/master/rdf-serving/src/main/jspx/test-rdf.jspx

I'd like to even ditch the dynamic content on the page and make it a static HTML page, rather than bother with more JSPX, but I don't feel strongly about it.

**Comment by kkasravi** [comment]
Ok. Does the README cover how to bring up the page or have the jspx's been integrated into the http server yet?

**Comment by srowen** [comment]
None of this is in the new project at all. In the name of simplicity I didn't integrate it yet, and, still hope to perhaps stick to a simple HTML page rather than get back into JSPX

**Comment by kkasravi** [comment]
I see. I'll take a look at the old pages.

**Comment by srowen** [comment]
Hehe, I think i actually finished this. There was very little to it. Feel free to review my handiwork or test it; I have only the most basic of unit tests for it.
