### ISSUE TITLE
KMeansUpdateIT fails / hangs

### ISSUE THREAD

**Issue by srowen** [OryxProject/oryx#117]
`KMeansUpdateIT` is disabled right now since it mysteriously hangs if you run it. The second call to `KMeans.train` never returns. I find that it doesn't seem to get scheduled even since the last thing in the logs is the call to `train`, and the Spark UI just shows the parent `foreachRDD` from `BatchLayer` executing -- in my case, I see it's stuck at 8 / 18 partitions.

Suneel has been investigating but I am current looking at it too.

**Comment by smarthi** [comment]
Issue happens due to KMeans.train() not being able to find the input RDDs when invoked over several batch intervals. The temporary fix for now is to cache() the RDDs before calling KMeans.train() and unpersist() following the call.
