### ISSUE TITLE
Random NPEs with RDFSpeedIT.testRDFSpeedClassification()

### ISSUE THREAD

**Issue by smarthi** [OryxProject/oryx#123]
Seeing the below test failures intermittently and they are not deterministic. The test does pass on a few occasions. 

{Code}
java.lang.NullPointerException
at com.cloudera.oryx.app.speed.rdf.RDFSpeedIT.testRDFSpeedClassification(RDFSpeedIT.java:160)
{Code}

Or 

{Code} 
java.lang.NullPointerException
at com.cloudera.oryx.app.speed.rdf.RDFSpeedIT.testRDFSpeedClassification(RDFSpeedIT.java:161)
{Code}

**Comment by smarthi** [comment]
Tried this a few times and tests passed locally, will leave this issue open until the next Travis build in case the test fails again.

**Comment by smarthi** [comment]
Closing this issue for now, Travis build passed a second time with no test failures.

**Comment by smarthi** [comment]
Reopening this issue as the test needs to be made more deterministic to avoid these random failures

**Comment by srowen** [comment]
I think I improved the test, to address the last seen failure, although that failure was not an NPE.

https://github.com/OryxProject/oryx/commit/b48894b1aa06565c66d8d8d1f5d2252fe00f1a0a
