### ISSUE TITLE
Consider using spark-submit for launch speed, batch layer

### ISSUE THREAD

**Issue by srowen** [OryxProject/oryx#154]
A simple, custom script is used to launch the Spark-based batch layer and speed layer. This has some pros and cons.

Pros:

- Allows all config to be in the `.conf` file and the job to be launched programmatically
- More control over script; can be integrated with serving layer script
- Bottles up some complexity of invoking Spark like setting external jars

Cons:

- Requires maintaining fragile classpath logic for particular environments

I wanted to record an open question to consider how much the pros outweigh cons over time.

**Comment by anhth12** [comment]
I think that ```ConfigUtils``` should add a method load a file config like this

```
ConfigFactory.parseFile(new File("conf/application.conf")).resolve()
```
and
```com.cloudera.oryx.batch.Main``` should have two way to call ```Config``` object: 
 - If arguments are specified, take the first argument as configuration file directory
 - If arguments are missing, use -Dconfig.file (```ConfigUtils.getDefaults```)

then submiting spark job would look like this
``` spark-submit --jars oryx-batch-2.0.0-SNAPSHOT.jar --class com.cloudera.oryx.batch.Main oryx-batch-2.0.0-SNAPSHOT.jar <directory to config file>```

**Comment by srowen** [comment]
If the idea is to make the config file optional, then it can simply be an optional flag. The way Typesafe Config works, just not specifying `config.file` works as you imagine. However, in this application, user configuration is definitely required. Defaults would never result in a working service. If the change is just to make the config file an argument rather than flag, hm, I'd prefer to keep the `--conf` flag here.

**Comment by srowen** [comment]
It occurs to me that it's possible to write a wrapper script that invokes `spark-submit` but reads arguments like executor memory from the single, standard config file. That removes one "pro" for the current approach.
