### ISSUE TITLE
Flaky test: BatchLayerIT.testBatchLayerMultipleReceivers

### ISSUE THREAD

**Issue by smarthi** [OryxProject/oryx#183]
```
BatchLayerIT.testBatchLayerMultipleReceivers:50->doTestBatchLayer:76->AbstractBatchIT.checkOutputData:128->Assert.assertEquals:645->Assert.failNotEquals:834->Assert.fail:88 Wrong count of data read expected:<600> but was:<588>
```

**Comment by srowen** [comment]
It should dump the counts that were actually observed in each interval in this case, for debugging. Was there more in the logs? I think this is another case where a little data doesn't make it into the final interval due to some delay. We might be able to just loosen the test.

**Comment by smarthi** [comment]
That's all there was in the logs, there was one other failure on the subsequent build run, pasting it here.

java.lang.AssertionError: Wrong count of data read expected:<2400> but was:<2315>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.cloudera.oryx.lambda.AbstractBatchIT.checkOutputData(AbstractBatchIT.java:128)
	at com.cloudera.oryx.ml.SimpleMLUpdateIT.testMLUpdate(SimpleMLUpdateIT.java:81)

Results :
Failed tests: 
  SimpleMLUpdateIT.testMLUpdate:81->AbstractBatchIT.checkOutputData:128->Assert.assertEquals:645->Assert.failNotEquals:834->Assert.fail:88 Wrong count of data read expected:<2400> but was:<2315>

**Comment by srowen** [comment]
(Use the back-ticks or else some of the error messages doesn't show correctly.)
The output would be higher up, due to https://github.com/OryxProject/oryx/blob/94ee7157e8f1c92c1b606669857e3f64378260db/oryx-lambda/src/test/java/com/cloudera/oryx/lambda/AbstractBatchIT.java#L116

This would help debug the situation. I haven't been able to reproduce it at the moment.

**Comment by srowen** [comment]
Oh NM, I can see them at https://travis-ci.org/OryxProject/oryx/jobs/52962270

**Comment by srowen** [comment]
I'm going to optimistically declare this fixed. We'll see.

**Comment by smarthi** [comment]
+1 to close this. Unlike the SpeedIT tests which were failing more often,
these don't have happen frequently.
