### ISSUE TITLE
Put modules into logical groupings; address packaged app consumers in README.md

### ISSUE THREAD

**Issue by srowen** [OryxProject/oryx#185]
I'm paraphrasing here, but @jhlch points out that there are at least two audiences who encounter the project: broadly, people looking for completed applications, and people looking for a framework to build on. The initial experience at the home page is unnecessarily confusing to both.

Concretely, the various modules are all at the top level, even though they probably fall into three broad groups:
- Framework (lambda tier, ML tier, common support packages)
- Applications
- Packaging modules

So one positive step could be to simply put the modules in subdirectories accordingly. The modules themselves would stay the same, just be organized more hierarchically in the source. This is a step towards (maybe, one day) separating these further into different repos, even. I'd like to stop just short of that for now.

Second, the homepage docs in `README.md` jump straight into a fairly framework-oriented discussion. Instead, both audiences should immediately find a link to what they want straight away at the top: a clearer link to the packaged apps and their endpoints for one audience, and then most of the current content for the framework audience.

I think these are two small but good steps forward.

**Comment by smarthi** [comment]
That's the feedback I have to from people to whom I had presented Oryx, so +1 to this.

**Comment by srowen** [comment]
So I am contemplating the following structure for modules:

- `framework`
    - `oryx-api`
    - `oryx-lambda`
    - `oryx-lambda-serving`
    - `oryx-ml`
    - `oryx-common`
    - `kafka-util`
    - `zk-util`
- `apps`
    - `conf` directory
    - `oryx-app-*`
    - `example`
- `deploy`
    - `bin` directory
    - `oryx-batch`
    - `oryx-speed`
    - `oryx-serving`

I think the other cruft has to stay at the top level for the root `pom.xml`. 
What do you think?

**Comment by srowen** [comment]
For the main `README.md`, I want to restructure as roughly:

- Current introductory paragraph
- Top level heading *Applications*, directing people quickly to the releases, cluster setup wiki, endpoints docs
- Top level heading *Framework* followed by just about all the existing content you see now

**Comment by jhlch** [comment]
I think that restructuring and adding of directories sounds good and sensible to me.

**Comment by smarthi** [comment]
+1.  That is a clean separation of core framework, ML application and the executors.  It will be easier now for someone to just work off the Framework jar to build on.

**Comment by srowen** [comment]
(PR for `README.md` coming soon)
