### ISSUE TITLE
ClassCastException jblas DoubleMatrix

### ISSUE THREAD

**Issue by anhth12** [OryxProject/oryx#186]
Hi,

I am new to Spark. And I think this problem is belong to Spark. But did you encounter any problem like this:
java.lang.ClassCastException: org.jblas.DoubleMatrix cannot be cast to org.jblas.DoubleMatrix
        org.apache.spark.mllib.recommendation.ALS$$anonfun$8.apply(ALS.scala:337)
        scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
        scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
        scala.collection.Iterator$class.foreach(Iterator.scala:727)
        scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
        scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
        scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
        scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
        org.apache.spark.rdd.RDD$$anonfun$22.apply(RDD.scala:895)
        org.apache.spark.rdd.RDD$$anonfun$22.apply(RDD.scala:895)
        org.apache.spark.SparkContext$$anonfun$26.apply(SparkContext.scala:1157)
        org.apache.spark.SparkContext$$anonfun$26.apply(SparkContext.scala:1157)
        org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:62)
        org.apache.spark.scheduler.Task.run(Task.scala:54)
        org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:177)
        java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        java.lang.Thread.run(Unknown Source)

Do you have any solution?

**Comment by srowen** [comment]
It's a strange problem since of course the two classes in the error are the same. It must be a classloader problem. How are you building and running Oryx?

**Comment by anhth12** [comment]
I found that I ran Oryx in Spark 1.1. I moved to Spark 1.2. This error does not happen again.

**Comment by smarthi** [comment]
Can we consider this issue closed now @anhth12 ??

**Comment by smarthi** [comment]
Resolved
