### ISSUE TITLE
Use new direct Kafka API + Spark 1.3.0

### ISSUE THREAD

**Issue by srowen** [OryxProject/oryx#192]
It's probably worth requiring Spark 1.3.0 to use the new Kafka API: http://spark.apache.org/docs/1.3.0/streaming-kafka-integration.html

**Comment by dsdinter** [comment]
I like that, I was actually going to ask about WAL introducing data duplication to avoid zero data loss. This new approach would solve that right?

**Comment by srowen** [comment]
I'm thinking of the direct approach described in that doc, and yes it should avoid data loss.

**Comment by ranjitiyer** [comment]
Sean, this is totally the wrong place to ask this question and my apologies in advance but do you think there are plans for developing a Kinesis Direct API similar to the Kafka Direct API?

**Comment by cfregly** [comment]
@ranjitiyer:  TD and I from databricks have been working on this over the past month.

the issue is that Kinesis doesn't offer "from and to" (only from) semantics for replay like Kinesis.  

additionally, the sequence numbers in Kinesis are not consecutive and deterministic like Kafka.

in short, spark 1.5 will have the closest we can get to a KinesisRDD like KafkaRDD, but not exactly the same impl.  at least once semantics will be guaranteed, however.

we've talked to a few folks from AWS/Kinesis about this, but not sure we'll get what we need here anytime soon.

**Comment by ranjitiyer** [comment]
@cfregly Thanks for your response. So would you say the big improvement over the Recevier based Kinesis connector is 1) Not requiring WAL 2) Solves the data loss problem (potentially inherent in the Receiver based connector)?

**Comment by cfregly** [comment]
@ranjitiyer:  correct.  the idea is that the buffered stream source (kafka/kinesis) are essentially acting as the WAL.  WALs are pessimistic, assume failure, and incur a performance hit on both the success and failure paths.  the direct approach is optimized for the happy path and only incurs a hit upon failure.

this is similar to how i describe the lightweight Spark RDD lineage concept in comparison to MapReduce/HDFS.  as i'm sure you know, lineage is optimized for the happy path and does not incur the penalty of writing to 3 HDFS replicas between every MapReduce stage.  individual partitions will get rebuilt from lineage only upon failure, etc.

good questions, ranjit.

**Comment by ranjitiyer** [comment]
Thanks so much for your response Chris, I am learning a lot! Couple more questions, if it's okay or if this forum is not the correct one, please let me know..

Does the Direct approach offer additional parallelism compared to the Receiver approach. The Receivers run as long running tasks inside the Executor and my understanding is that if you create two Receivers (KinesisUtil.createStream twice) they potentially get put on two Workers.

How do the RDDs in the Direct approach translate? If I had two Worker nodes, does the act of calling KinesisUtil.createDirectStream result in two entities sitting on each Worker simultaneously reading from Kinesis shards? Do they run as long running tasks?

**Comment by srowen** [comment]
While you're welcome to chat here, this might be more useful for more people on the Spark list.
