### ISSUE TITLE
questions on training the model

### ISSUE THREAD

**Issue by thanigaiv** [OryxProject/oryx#203]
In Oryx2, can you please explain how to train, tweak and evaluate a model using different hyperparams? Also, does the configuration file be used for sending algorithm parameters like below:

als {
        decay {
            factor=1
            zero-threshold=0
        }
        hyperparams {
            alpha=1
            features=10
            lambda=0.001
        }
        implicit=true
        iterations=10
        no-known-items=false
        rescorer-provider-class=null
    }

**Comment by smarthi** [comment]
I can answer this sometime today if Sean doesn't beat me to it 😏

**Comment by srowen** [comment]
Please use the mailing list for questions; this is for discussing issues or improvements.
https://groups.google.com/a/cloudera.org/forum/#!forum/oryx-user

See the application-specific hyperparams at https://github.com/OryxProject/oryx/blob/master/app/oryx-app-common/src/main/resources/reference.conf

The trick is that you can specify a range of hyperparams like: `alpha = [1,40]`.  You can do this for many hyperparams at once. Then set `ml.eval.candidates` to a value greater than 1 to try several combinations of values and take the best one.

**Comment by thanigaiv** [comment]
Thank you!
