### ISSUE TITLE
How REST API is implemented

### ISSUE THREAD

**Issue by niranjanMaisnam** [OryxProject/oryx#210]
Hi,

Can someone help me how rest request are handled in Oryx 2. I looked into the code I find Tomcat instance being built is it that Oryx 2 uses Tomcat instances to serve REST API.

Please help.

Thanks

**Comment by smarthi** [comment]
Oryx 2 Serving layer starts up a Tomcat instance that services REST
endpoints.

See this
http://oryxproject.github.io/oryx/docs/index.html#API_Endpoint_Reference
for the available endpoints.

**Comment by niranjanMaisnam** [comment]
Thanks smarthi
