### ISSUE TITLE
Too many connections to Kafka

### ISSUE THREAD

**Issue by srowen** [OryxProject/oryx#216]
Originally I thought the problem and solution were: `/pref`, `/ingest` endpoints instantiated on every request and open new Kafka producer each time. This ends up maxing out the number of concurrent Kafka connections under load. `@Singleton` in JAX-RS should solve it.

Now I think it's because the `TopicProducer` sends individual messages synchronously which doesn't scale.

**Comment by srowen** [comment]
I am not sure this was the problem, but this is a good idea anyway, and is done.

**Comment by dsdinter** [comment]
I actually faced that issue and bumped up max number of connections on the Kafka brokers to solve it.
Sounds good anyway.

**Comment by srowen** [comment]
Yeah I also increased the number of connections to resolve it, but I don't like the solution.

I think we need to use the async producer to send messages in batch. That works well locally; haven't tested it on the cluster yet. It revealed another small bug in how `TopicProducer` is handled that I'm also addressing now. 

Will post more when I have some info that it works, but am reopening in the meantime.
