### ISSUE TITLE
Consider porting CandidateFilter

### ISSUE THREAD

**Issue by srowen** [OryxProject/oryx#219]
Version 1 implemented a type of "candidate filter" for ALS. This is to consider porting the candidate filter concept.

**Comment by srowen** [comment]
Given LSH is implemented, and that was most of the use case for this, and the rest of the use cases can also be answered with rescorer in general, I'm closing this.

**Comment by nmathon** [comment]
Sean,

Are you sure CandidateFilter is not a good feature ? I have some models with more than 10M items but only 1M available to recommendation. RescorerParams works fine but it filters items in real-time. I was hoping something to do more "background filtering" and CandidateFilter was a good way to do this.

Nicolas
