### ISSUE TITLE
split train and test bug?

### ISSUE THREAD

**Issue by jinsu** [OryxProject/oryx#221]
Hi Sean,

The default testFraction is set to 0.1.

https://github.com/OryxProject/oryx/blob/master/app/oryx-app-mllib/src/main/java/com/cloudera/oryx/app/batch/mllib/als/ALSUpdate.java#L233

I think that line should be:
`final long approxTestTrainBoundary = minTime + (long) (1.0 - getTestFraction() * (maxTime - minTime));`?

**Comment by srowen** [comment]
Ah, yes good catch!

**Comment by andrewcz** [comment]
Was just wondering,
Not sure were this comment should be placed
but will there be more focus on visualisation of the machine learning algorithms in the examples.

Many thanks
Andrew

**Comment by srowen** [comment]
Don't think that is related to this issue?
No oryx has nothing to do with visualization at this point. Very operational only
