### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by moritzschaefer** [OryxProject/oryx#237]
Is python support planned for writing oryx Apps?

**Comment by srowen** [comment]
I strongly doubt it. Pyspark notwithstanding, it's quite a different environment to integrate with. My expectation is that Python is generally used by the exploratory analytics community, and that operational analytics is typically built by people who are using Java, Scala. The audience here is the latter.

**Comment by srowen** [comment]
I don't want to convey that nothing can ever happen here with Python, but in the foresesable future, no, so I'm going to close this. Later it could be reopened.
