### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by timshenkao** [OryxProject/oryx#256]
Hi!
I apologize that I write my message here as I didn't find any other mean of communication.
I got interested in Oryx very much. And I'd like to participate, to help to develop the project.

Is there any roadmap: features, algorithms should be implemented, systems should be integrated with, etc.? Do you consider to extend Oryx with DeepLearning methods or Graph Mining algorithms?

I found that you're going to rewrite completely using Java 8. Do you intend to rewrite everything in Scala (as Cloudera announced "One platform initiative")? 

Thanks!

**Comment by srowen** [comment]
The best place is https://groups.google.com/a/cloudera.org/forum/#!forum/oryx-user so I hope you won't mind that I close this.

You can see a few possible issues or roadmap items in this repo. However for the moment there is nothing big planned. I'd like to make it nice and stable and see how real-world use guides future work.

The most useful thing is to try running this on a real data set and see how the process of setup, deployment, testing goes. Any errors? things that can go better?

Yes it's Java-based for the foreseeable future. I'd like to move to Java 8 soonish, but not now. As you can see it's already done in the branch `Java8` and it takes out about 1000 lines of code. This closes the gap a little bit with Scala.

I'd almost have been happy to create this in Scala but there are a number of small downsides to it -- less mature build tools, not as widely known, not actually that advantageous here.

"One Platform" doesn't have anything to do with Scala actually.
