### ISSUE TITLE
Remove compute-classpath.sh

### ISSUE THREAD

**Issue by srowen** [OryxProject/oryx#265]
`compute-classpath.sh` is ugly. Most of its use has been removed by using `spark-submit`. However, the Spark-based layers still need access to Kafka and some Zookeeper classes as they function as Kafka clients directly. And, the serving layer needs the same, as well as some Hadoop classes generally, as a client of Kafka and HDFS as well. (And YARN's distributed shell if running on YARN.)

One fairly clean solution is to simply build these into the assembly JARs. This risks runtime incompatibilities with the cluster and also means bringing back the idea of builds specific to a version of Kafka, or Hadoop. It's also a little disappointing or inconsistent, as the Spark-based apps can use the cluster's Spark distribution in the main.

Intermediate improvements are possible:
- Don't use the `spark-examples` JAR. Use Kafka (client) JARs only
- Refactor `compute-classpath.sh` to take arguments like `serving yarn`, and emit only the classpath elements needed for that layer / deployment.
- Try to automatically find the JARs by looking for well-known env variables like `HADOOP_HOME`

**Comment by mzorro** [comment]
I have runtime dependency problem, `compute-classpath.sh` is not working, because our servers isn't built on CDH. So I just add runtime dependencies into each layer's `pom.xml` file. Here is what I add.

for the batch and speed layer (`oryx-batch` and `oryx-speed` project)
```
<dependency>
  <groupId>org.apache.kafka</groupId>
  <artifactId>kafka_${scala.minor.version}</artifactId>
  <version>${kafka.version}</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>org.apache.spark</groupId>
  <artifactId>spark-streaming-kafka-0-8_${scala.minor.version}</artifactId>
  <version>${spark.version}</version>
  <scope>runtime</scope>
</dependency>
```

for the serving layer (`oryx-serving` project)
```
<dependency>
  <groupId>org.scala-lang</groupId>
  <artifactId>scala-library</artifactId>
  <version>${scala.complete.version}</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>org.apache.spark</groupId>
  <artifactId>spark-core_${scala.minor.version}</artifactId>
  <version>${spark.version}</version>
  <scope>runtime</scope>
  <exclusions>
    <exclusion>
      <groupId>com.sun.jersey</groupId>
      <artifactId>jersey-core</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>org.apache.spark</groupId>
  <artifactId>spark-streaming_${scala.minor.version}</artifactId>
  <version>${spark.version}</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>org.apache.spark</groupId>
  <artifactId>spark-streaming-kafka-0-8_${scala.minor.version}</artifactId>
  <version>${spark.version}</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>org.apache.spark</groupId>
  <artifactId>spark-mllib_${scala.minor.version}</artifactId>
  <version>${spark.version}</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>org.apache.kafka</groupId>
  <artifactId>kafka_${scala.minor.version}</artifactId>
  <version>${kafka.version}</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>org.apache.zookeeper</groupId>
  <artifactId>zookeeper</artifactId>
  <version>${zookeeper.version}</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>org.apache.hadoop</groupId>
  <artifactId>hadoop-auth</artifactId>
  <version>${hadoop.version}</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>org.apache.hadoop</groupId>
  <artifactId>hadoop-common</artifactId>
  <version>${hadoop.version}</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>org.apache.hadoop</groupId>
  <artifactId>hadoop-hdfs</artifactId>
  <version>${hadoop.version}</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>org.apache.htrace</groupId>
  <artifactId>htrace-core</artifactId>
  <version>4.0.0-incubating</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>commons-cli</groupId>
  <artifactId>commons-cli</artifactId>
  <version>1.3.1</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>commons-collections</groupId>
  <artifactId>commons-collections</artifactId>
  <version>3.2.2</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>commons-configuration</groupId>
  <artifactId>commons-configuration</artifactId>
  <version>1.10</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>com.google.protobuf</groupId>
  <artifactId>protobuf-java</artifactId>
  <version>2.5.0</version>
  <scope>runtime</scope>
</dependency>
<dependency>
  <groupId>org.xerial.snappy</groupId>
  <artifactId>snappy-java</artifactId>
  <scope>runtime</scope>
</dependency>
```

This is easyly working for me, but may has some problems as @srowen says above.
Also I hasn't try it on YARN it, right now I'm running it on SparkAlone, so I didn't use the script `oryx-run.sh` either.

**Comment by srowen** [comment]
As of 2.3.0, `compute-classpath.sh` is no longer used for anything except the serving layer's classpath, at least.

**Comment by srowen** [comment]
The likely ultimate solution here is to produce two artifacts: one without dependencies and one with all built in. The script becomes an ancillary helper for deployments that really want to match with a cluster's deployed classpath artifacts. For cases where matching versions isn't a problem, the full assembly is more convenient and self-contained.
