### ISSUE TITLE
Oryx 2.1.2: "org.apache.hadoop.fs.FSDataInputStream" not found on CDH 5.5.1 Cluster

### ISSUE THREAD

**Issue by bash-horatio** [OryxProject/oryx#279]
After reading release and bug-fixed notes, I think 2.1.2 is pretty good version, think for @srowen's contribution for this.

 Since I have to remain a CDH 5.4.x cluster with Oryx 2.0.x running on it, I deploy a new cluster for 2.1.x branch.Unfortunately, this try seemed to be more difficult than I imagined. **Some dependency library has changed on CDH 5.5.1 while compute-classpath.sh and oryx-run.sh on 2.1.2 are a few different from those on 2.0.x.**

Everything was still OK until I started to run Oryx with old als.conf for 2.0.0. Exceptions were thrown by batch and speed : 
#### Batch
```
spark-submit --master yarn-client --name OryxBatchLayer-ALSTest --class com.cloudera.oryx.batch.Main      --jars /opt/cloudera/parcels/CDH/jars/spark-examples-1.5.0-cdh5.5.1-hadoop2.6.0-cdh5.5.1.jar --files test.conf --driver-memory 512m      --driver-java-options "-Dconfig.file=test.conf" --executor-memory 1g --executor-cores 1      --conf spark.executor.extraJavaOptions="-Dconfig.file=test.conf" --conf spark.ui.port=20000 --conf spark.io.compression.codec=lzf --conf spark.logConf=true --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.speculation=true --conf spark.ui.showConsoleProgress=false --num-executors=3 oryx-batch-2.jar

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
	at org.apache.spark.deploy.SparkSubmitArguments.handle(SparkSubmitArguments.scala:394)
	at org.apache.spark.launcher.SparkSubmitOptionParser.parse(SparkSubmitOptionParser.java:163)
	at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:97)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:113)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 5 more

```

#### Speed
```
spark-submit --master yarn-client --name OryxSpeedLayer-ALSTest --class com.cloudera.oryx.speed.Main      --jars /opt/cloudera/parcels/CDH/jars/spark-examples-1.5.0-cdh5.5.1-hadoop2.6.0-cdh5.5.1.jar --files test.conf --driver-memory 256m      --driver-java-options "-Dconfig.file=test.conf" --executor-memory 512m --executor-cores 1      --conf spark.executor.extraJavaOptions="-Dconfig.file=test.conf" --conf spark.ui.port=20001 --conf spark.io.compression.codec=lzf --conf spark.logConf=true --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.speculation=true --conf spark.ui.showConsoleProgress=false --num-executors=2 oryx-speed-2.jar

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
	at org.apache.spark.deploy.SparkSubmitArguments.handle(SparkSubmitArguments.scala:394)
	at org.apache.spark.launcher.SparkSubmitOptionParser.parse(SparkSubmitOptionParser.java:163)
	at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:97)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:113)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 5 more
```

I guessed Oryx could find some hadoop's libs but I have no idea how to solve this problem.
I found something similar on stackoverflow, something wrong on my Spark's configurations?
> ![NoClassDefFoundError com.apache.hadoop.fs.FSDataInputStream when execute spark-shell](http://stackoverflow.com/questions/30906412/noclassdeffounderror-com-apache-hadoop-fs-fsdatainputstream-when-execute-spark-s)

**Comment by srowen** [comment]
Yes, I'm afraid that's not going to work. 2.1 requires CDH 5.5. I'm not clear whether you are saying you're using CDH 5.5 or 5.4, and whether you are using old scripts with the new version (you can't do that).

The classpaths are a little different. Really, the whole `compute-classpath.sh` mechanism is clunky. It avoids one problem (different builds) but causes another (fragile env-specific dependencies). But it still wouldn't mean you could use 2.1 with CDH 5.4 since it has Spark 1.3.

In 2.2.x, `spark-submit` gets used for Spark jobs so the classpath complexity goes away to a large extent.

**Comment by bash-horatio** [comment]
I run Oryx 2.1.2 on CDH 5.5.1 with old configuration of ALS algorithm for Oryx 2.0.1.Does it master?

**Comment by srowen** [comment]
That much is fine. I notice from your snippet that you're not actually running the binaries from this project with the supplied script. That won't work either, in general, or at least you're on your own.

**Comment by bash-horatio** [comment]
I just wrote a script to start three layers more simply, and it calls oryx-run.sh exactly from this project.
As for the binaries, I changed their names such changing "oryx-batch-2.1.2.jar" to "oryx-batch-2.jar"

**Comment by srowen** [comment]
Hm, how does it run them then? I don't see the relationship to the `spark-submit` you posted above.

**Comment by bash-horatio** [comment]
What I posted above is the output of `oryx batch ` and `oryx speed` in `start()` method of my script: 

```
Instance=`basename $PWD`
Conf="$Instance".conf
Pids="./pids"

oryx() {
    ./oryx-run.sh $1 --conf $Conf 
    if [ $? -eq 0 ]; then
        echo "$1 layer started, done"
    else echo "Failed to start $1 layer"
    fi
    sleep 3
    ps -ef | grep $Instance | grep $1 | awk '{print $2}' >> $Pids
}

start() {
    ./oryx-run.sh kafka-setup --conf $Conf
    echo "Starting Oryx2 instance -- $Instance..."
    if [ -f $Pids ]; then
        pids=`cat $Pids`
        echo -e "Oryx running as:\n$pids"
    else
        oryx batch
        oryx speed
        oryx serving
    fi
}

...
...

case "$1" in
    start)
        start
        ;;
    stop)
        # SIGABRT
        stop -6
        ;;
    restart)
        # SIGABRT
        stop -6
        start
        ;;
    kill)
        # SIGKILL
        stop -9
        ;;
    *)
        echo "Usage: $0 <start | stop | restart | kill>"
        ;;
esac
```

**Comment by bash-horatio** [comment]
I followed the link posted yesterday, and the exceptions gone.
Oryx on my node(with CM5.5.1 installed) could not find proper configurations, because there are none of services(Datanode, Node manager and so on.) running on it. I planed to make it as **a "client"** of spark jobs, which doesn't get involved in any computation at all.

So I created relevant services on this node but stopped them, and all things work now.Thanks for help!

**Comment by srowen** [comment]
Ah, that was my next question: do the libraries even exist on the machine? it assumes you're running inside the cluster, and needs to be an edge node at least.

**Comment by bash-horatio** [comment]
Yep, this node is a part of CDH cluster. I installed CM 5.5 and deployed CDH 5.5.1 parcel on it. The point here is that if I just **leave it with default configuration** (*without creating Datanode ,NodeManager and 
Spark Gateway services on it*), Oryx/spark-submit can't read proper configuratons of Spark, Hadoop and Yarn as other nodes do. Maybe "edge node" you refer to is what I want, and could you explain what's the meaning of "**edge node**"?

**Comment by srowen** [comment]
Yes it has to be at least a Spark gateway, to deploy the Spark libs and files. It has to be a machine you can `spark-submit` from. "Edge node" is just another word for "gateway"

**Comment by bash-horatio** [comment]
Thanks a lot. Now I am pretty sure that I deploy this node as a "edge node", which satisfies my requirements perfectly.
