### ISSUE TITLE
User-based Recommendation and Item-based Recommendation by oryx

### ISSUE THREAD

**Issue by TopSpoofer** [OryxProject/oryx#281]
How can I   realize User-based Recommendation and  Item-based Recommendation by oryx2? what is the data format for User-based Recommendation  and Item-based Recommendation?

**Comment by srowen** [comment]
You would need to write new application-level code for a batch, speed and serving layer. You could reuse a lot of the existing ALS-based ones. However the logic to make the model would change, and update it, and make recommendations. It's an entirely different type of model. Not hard, but you would be making your own app.
