### ISSUE TITLE
src/test/java is not found?

### ISSUE THREAD

**Issue by dahaian** [OryxProject/oryx#286]
I import the oryx project into the eclipse.But it has some wrong.It is src/test/java is missing.I do not know why you delete it?The maven may be requst the src/test/java.How can I do?

**Comment by srowen** [comment]
I don't know what you mean? no directories have been deleted. There are `src/test/java` dirs where they should be, and the Travis builds pass: https://travis-ci.org/OryxProject/oryx

**Comment by dahaian** [comment]
It is the oryx/app/example/src/main/.This dir has not /test dir.The eclipse flag as a error.

**Comment by srowen** [comment]
There are not supposed to be tests in the example module. This is entirely fine. It's an Eclipse problem.

**Comment by dahaian** [comment]
Oh,It's an Eclipse problem.Please tell me what IDE do you use?
