### ISSUE TITLE
Cannot infer type arguments for ScalaSpeedModelManagerAdapter<>	SpeedLayer.java	/oryx-lambda/src/main/java/com/cloudera/oryx/lambda/speed

### ISSUE THREAD

**Issue by dahaian** [OryxProject/oryx#288]
The Eclipse report this an error.I see the  oryx/framework/oryx-lambda/src/main/java/com/cloudera/oryx/lambda/speed/ScalaSpeedModelManagerAdapter.java. You define `ScalaSpeedModelManagerAdapter<K,M,U>`.But you use ScalaSpeedModelManagerAdapter<> on  oryx/framework/oryx-lambda/src/main/java/com/cloudera/oryx/lambda/speed/SpeedLayer.java. Where is the parameter `<K,M,U>`?

**Comment by srowen** [comment]
It sounds like you have set the language level to something below Java 8. The supplied Maven build configures all of this correctly, and you should be using that (via Eclipse if you like). The build and source are correct. Again, see https://travis-ci.org/OryxProject/oryx  This shows the build current compiles and passes all tests.

**Comment by dahaian** [comment]
Oh,thinks

**Comment by dahaian** [comment]
@srowen ,What scala version do you use?I see you write `<scala.minor.version>2.10</scala.minor.version>
    <scala.complete.version>${scala.minor.version}.5</scala.complete.version>`.
But if I use scala version 2.10.The oryx-api project can not be resolved.If I use scala version 2.11.The oryx-api project can be resolved.But the Eclipse flag error that akka-actor_2.10-2.2.3-shaded-protobuf.jar of example build path is cross-compiled with an incompatible version of Scala (2.10.0). My Eclipse version is Mars.4.5.2.
Pleaese help me.Thanks.

**Comment by srowen** [comment]
The build uses Scala 2.10 or Scala 2.11. I'm not sure what you mean. You can see the build works including the 2.11 profile, again in https://travis-ci.org/OryxProject/oryx  This is again not a project problem

**Comment by dahaian** [comment]
But I still can not build success in Eclipse.My Eclipse version is Mars.4.5.2.If I build use Scala 2.10 in oryx-api project.The Eclipse flag error that the oryx-api project can not be resolved.If I bulid use Scala 2.11 in oryx-api project.The Eclipse flag error that the akka-actor_2.10-2.2.3-shaded-protobuf.jar of oryx-api build path is cross-compiled with an incompatible version of Scala (2.10.0). 
Can you help me build seccess in Eclipse?Thanks.
