### ISSUE TITLE
java.lang.ClassCastException: class kafka.serializer.StringDecoder  happen in oryx-2.4.0

### ISSUE THREAD

**Issue by jessica0530** [OryxProject/oryx#332]
java.lang.ClassCastException: class kafka.serializer.StringDecoder
        at java.lang.Class.asSubclass(Class.java:3404)
        at com.cloudera.oryx.common.lang.ClassUtils.loadClass(ClassUtils.java:54)
        at com.cloudera.oryx.lambda.serving.ModelManagerListener.init(ModelManagerListener.java:96)

 this error happen in  this Code
this.updateDecoderClass = (Class<? extends Deserializer<U>>) ClassUtils.loadClass(
config.getString("oryx.update-topic.message.decoder-class"), Deserializer.class);

"oryx.update-topic.message.decoder-class" is  kafka.serializer.StringDecoder 

How can I fix this ?? help

**Comment by srowen** [comment]
You're using outdated configuration. 2.4.x requires Kafka 0.10, and the classes have changed. You need a `Deserializer` in `org.apache.kafka.common.serialization`. See https://github.com/OryxProject/oryx/blob/oryx-2.4.0/framework/oryx-common/src/main/resources/reference.conf#L44
