### ISSUE TITLE
Can't run speed or batch layers

### ISSUE THREAD

**Issue by wones0120** [OryxProject/oryx#333]
We are trying to run 2.4.1 on CDH 5.11 with what we believe to be all of the correct requirements.

In the spark-env.sh, the SPARK_KAFKA_VERSION=${SPARK_KAFKA_VERSION:-'0.9'} which causes 
the following error:

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.KafkaConsumer.subscribe

When we switch it to '0.10', we get this error.

ge 0.0 (TID 3, oryx-dn1.eastus.cloudapp.azure.com, executor 1): java.lang.UnsupportedClassVersionError: com/cloudera/oryx/lambda/speed/SpeedLayer : Unsupported major.minor version 52.0

Not really sure how to proceed.  It is either a missing method or unsupported version.  Again, to the best of our knowledge, we have followed all of the instructions.

We did have to include:
      <dependency>
        <groupId>org.apache.servicemix.bundles</groupId>
        <artifactId>org.apache.servicemix.bundles.kafka_2.10</artifactId>
        <version>0.10.2.1_1</version>
      </dependency>
in the batch and speed pom files to get it to work.  We initially started with the jar files from git but switched to mvn to overcome that error.

Any help would be appreciated as we are basically giving up.

**Comment by srowen** [comment]
Yes, it certainly requires Kafka 0.10.
Unsupported major/minor 52 means you are running with Java 7, when you need Java 8.

**Comment by wones0120** [comment]
Found this is the /etc/spark2/conf.cloudera.spark2_on_yarn/spark-env.sh.  We ultimately had to change the version to be '0.10' to get it to work in addition to making sure the JDK1.8 was on all of the nodes correctly.
 
# Add the Kafka jars configured by the user to the classpath.
SPARK_DIST_CLASSPATH=
SPARK_KAFKA_VERSION=${SPARK_KAFKA_VERSION:-'0.9'}
case "$SPARK_KAFKA_VERSION" in
  0.9)
    SPARK_DIST_CLASSPATH="$SPARK_HOME/kafka-0.9/*"
    ;;
  0.10)
    SPARK_DIST_CLASSPATH="$SPARK_HOME/kafka-0.10/*"
    ;;
  None)
    ;;
  *)
    echo "Invalid Kafka version: $SPARK_KAFKA_VERSION"
    exit 1
    ;;
esac

**Comment by srowen** [comment]
You shouldn't need to modify any scripts; I don't need to on my cluster. It's just a client of Kafka, and Kafka client libs are already in the app.
