### ISSUE TITLE
Error while runnig Oryx  batch 

### ISSUE THREAD

**Issue by MalekSoltani** [OryxProject/oryx#344]
Hello, 
I'm using Oryx 2.5 on CHD 5.12 , when i tried to run oryx-run.sh batch i got the following error : 

spark2-submit --master yarn --deploy-mode client      --name OryxBatchLayer-ALSExample --class com.cloudera.oryx.batch.Main  --files oryx.conf      --driver-memory 1g --driver-java-options "-Dconfig.file=oryx.conf"      --executor-memory 1g --executor-cores 2      --conf spark.executor.extraJavaOptions="-Dconfig.file=oryx.conf" --conf spark.ui.port=4040 --conf spark.io.compression.codec=lzf --conf spark.logConf=true --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.speculation=true --conf spark.ui.showConsoleProgress=false --num-executors=2 oryx-batch-2.5.0.jar
bash: /usr/bin/spark2-submit: cannot execute binary file

**Comment by srowen** [comment]
Can you `spark2-submit` anything? that seems to say the script itself isn't executable. It also isn't where the script would live CDH. Did you actually manually install it?
