### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/collection/Seq

### ISSUE THREAD

**Issue by Double1996** [OryxProject/oryx#346]
when I  RUN  serving

**Comment by srowen** [comment]
I'll answer this where you asked on the mailing list.

**Comment by Double1996** [comment]
THANKS 

> 在 2018年7月21日，下午10:53，Sean Owen <notifications@github.com> 写道：
> 
> Closed #346 <https://github.com/OryxProject/oryx/issues/346>.
> 
>

**Comment by Double1996** [comment]
Do you have any instant messaging? I'm in a hurry about this question
