### ISSUE TITLE
Reseting model

### ISSUE THREAD

**Issue by stiv-yakovenko** [OryxProject/oryx#352]
I have some recommendation data in oryx. How can I remove everything I had sent there without reformatting hdfs?

**Comment by srowen** [comment]
You can just delete data and or models from the data and model dirs you set up on HDFS. You may also need to delete the Kafka topics to be sure they are empty.

**Comment by stiv-yakovenko** [comment]
I am still not able to reset model. Initially model is in place:

![image](https://user-images.githubusercontent.com/4163254/45473087-39d7fd80-b760-11e8-9a82-c13e9fe23338.png)

Now I kill hdfs, yarn, oryx-batch, oryx-serving, oryx-speed:

![image](https://user-images.githubusercontent.com/4163254/45473439-4446c700-b761-11e8-8193-7ef963cc8e4c.png)

Now I delete all hdfs files and format hdfs the partition:

![image](https://user-images.githubusercontent.com/4163254/45473520-7c4e0a00-b761-11e8-8b8b-3d6a86502d06.png)

And recreate kafka topics:

![image](https://user-images.githubusercontent.com/4163254/45473645-c6cf8680-b761-11e8-9ccd-738a4cfde81c.png)

After restarting yarn, hdfs, orix-* I still see model not being reset:

![image](https://user-images.githubusercontent.com/4163254/45473783-2af24a80-b762-11e8-8c9c-43e0db0daa15.png)

It looks like there is some inner cache somewhere inside one of layers, how can I reset it?

**Comment by srowen** [comment]
There are still a number of possibilities, and I think they're specific to your deployment.

- Are you sure you killed the serving process? I'm not clear from the text above. That isn't using the script from the project.
- Are you sure you deleted the topics? this shows they existed already, not deleted.
- Are you sure you are deleting the files and topics your config references?
